[Instagram]
patches-source = "crimera/piko-newx"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
patches-version = "dev"
cli-version = "dev"

riplib = true

#apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
#uptodown-dlurl = "https://instagram.en.uptodown.com/android"
direct-dlurl = "https://github.com/Ravi-Kishor/apk-archive/releases/download/instagram-test/com.instagram.android.apkm"
